sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t krngrngtamu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krngrngtamu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-application"
  env: "Dockerreactapplication-env"
  bucket_name: "elasticbeanstalk-eu-west-2-109871241276"
  bucket_path: "docker-react-application"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws-secret-key
